#include "main_char.hh"
#include "utils.hh"
using namespace std;
using namespace pro2;


// Color codes
const int _ = -1;
const int r = pro2::red;
const int s = pro2::beige;
const int b = pro2::blue;
const int y = pro2::yellow;
const int h = pro2::black;
const int g = pro2::gray;
const int w = pro2::brown;
const int e = pro2::green;
const int i = pro2::white;
const int o = pro2::orange;
const int p = pro2::purple;

// clang-format off
// Mario sprites
const vector<vector<int>> MainChar::mario_sprite_normal_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, r, b, r, r, r, _, _, _, _},
    {_, r, r, r, b, r, r, b, r, r, r, _},
    {r, r, r, r, b, b, b, b, r, r, r, r},
    {g, g, r, b, y, b, b, y, b, r, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::mario_sprite_medium_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, r, b, r, r, r, _, _, _, _},
    {_, r, r, r, b, r, r, b, r, r, r, _},
    {r, r, r, r, b, b, b, b, r, r, r, r},
    {r, r, r, b, y, b, b, y, b, r, r, r},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::mario_sprite_big_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, r, b, r, r, r, _, _, _, _},
    {_, r, r, r, b, r, r, b, r, r, r, _},
    {r, r, r, r, b, b, b, b, r, r, r, r},
    {r, r, r, b, b, b, b, b, b, r, r, r},
    {r, r, b, b, y, b, b, y, b, b, r, r},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::mario_sprite_normal_walk1_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, r, b, r, r, r, _, _, _, _},
    {_, r, r, r, b, r, r, b, r, r, r, _},
    {r, r, r, r, b, b, b, b, r, r, r, r},
    {g, g, r, b, y, b, b, y, b, r, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::mario_sprite_normal_walk2_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, r, b, r, r, r, r, _, _, _},
    {_, _, r, r, b, r, r, b, r, r, _, _},
    {_, _, r, r, b, b, b, b, r, r, _, _},
    {_, _, g, g, b, b, b, y, b, r, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::mario_sprite_normal_walk3_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};
const vector<vector<int>> MainChar::mario_sprite_big_walk1_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, r, b, r, r, r, _, _, _, _},
    {_, r, r, r, b, r, r, b, r, r, r, _},
    {r, r, r, r, b, b, b, b, r, r, r, r},
    {r, r, r, b, b, b, b, b, b, r, r, r},
    {r, r, b, b, y, b, b, y, b, b, r, r},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::mario_sprite_big_walk2_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, r, b, r, r, r, r, _, _, _},
    {_, _, r, r, b, r, r, b, r, r, _, _},
    {_, _, r, r, b, r, r, b, r, r, _, _},
    {_, _, r, r, b, b, b, b, r, r, _, _},
    {_, _, b, b, b, b, b, y, b, r, _, _},
    {_, _, g, g, b, b, b, b, b, r, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::mario_sprite_big_walk3_ = {
    {_, _, _, r, r, r, r, r, _, _, _, _},
    {_, _, r, r, r, r, r, r, r, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, r, r, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};

// Luigi sprites
const vector<vector<int>> MainChar::luigi_sprite_normal_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, e, e, b, e, e, e, _, _, _, _},
    {_, e, e, e, b, e, e, b, e, e, e, _},
    {e, e, e, e, b, b, b, b, e, e, e, e},
    {g, g, e, b, y, b, b, y, b, e, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::luigi_sprite_medium_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, e, e, b, e, e, e, _, _, _, _},
    {_, e, e, e, b, e, e, b, e, e, e, _},
    {e, e, e, e, b, b, b, b, e, e, e, e},
    {e, e, e, b, y, b, b, y, b, e, e, e},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::luigi_sprite_big_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, e, e, b, e, e, e, _, _, _, _},
    {_, e, e, e, b, e, e, b, e, e, e, _},
    {e, e, e, e, b, b, b, b, e, e, e, e},
    {e, e, e, b, b, b, b, b, b, e, e, e},
    {e, e, b, b, y, b, b, y, b, b, e, e},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::luigi_sprite_normal_walk1_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, e, e, b, e, e, e, _, _, _, _},
    {_, e, e, e, b, e, e, b, e, e, e, _},
    {e, e, e, e, b, b, b, b, e, e, e, e},
    {g, g, e, b, y, b, b, y, b, e, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::luigi_sprite_normal_walk2_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, e, b, e, e, e, e, _, _, _},
    {_, _, e, e, b, e, e, b, e, e, _, _},
    {_, _, e, e, b, b, b, b, e, e, _, _},
    {_, _, g, g, b, b, b, y, b, e, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::luigi_sprite_normal_walk3_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};
const vector<vector<int>> MainChar::luigi_sprite_big_walk1_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, e, e, b, e, e, e, _, _, _, _},
    {_, e, e, e, b, e, e, b, e, e, e, _},
    {e, e, e, e, b, b, b, b, e, e, e, e},
    {e, e, e, b, b, b, b, b, b, e, e, e},
    {e, e, b, b, y, b, b, y, b, b, e, e},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::luigi_sprite_big_walk2_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, e, b, e, e, e, e, _, _, _},
    {_, _, e, e, b, e, e, b, e, e, _, _},
    {_, _, e, e, b, e, e, b, e, e, _, _},
    {_, _, e, e, b, b, b, b, e, e, _, _},
    {_, _, b, b, b, b, b, y, b, e, _, _},
    {_, _, g, g, b, b, b, b, b, e, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::luigi_sprite_big_walk3_ = {
    {_, _, _, e, e, e, e, e, _, _, _, _},
    {_, _, e, e, e, e, e, e, e, e, e, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, e, e, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};

// Star mode
const vector<vector<int>> MainChar::starmode_sprite_normal_ = {
    {_, _, _, r, o, o, y, e, _, _, _, _},
    {_, _, r, r, o, y, y, e, e, p, p, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, o, b, e, e, e, _, _, _, _},
    {_, r, o, y, b, e, e, b, e, p, p, _},
    {r, r, o, y, b, b, b, b, p, p, p, p},
    {g, g, y, b, y, b, b, y, b, p, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::starmode_sprite_medium_ = {
    {_, _, _, r, r, o, y, y, _, _, _, _},
    {_, _, r, r, o, o, y, e, e, p, p, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, o, b, y, y, e, _, _, _, _},
    {_, r, r, o, b, y, e, b, e, e, p, _},
    {r, r, o, o, b, b, b, b, e, p, p, p},
    {r, o, o, b, y, b, b, y, b, p, p, p},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::starmode_sprite_big_ = {
    {_, _, _, r, r, o, y, y, _, _, _, _},
    {_, _, r, r, o, o, y, e, e, p, p, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, r, o, b, y, y, e, _, _, _, _},
    {_, r, r, o, b, y, e, b, e, e, p, _},
    {r, r, o, o, b, b, b, b, e, e, p, p},
    {r, o, o, b, b, b, b, b, b, p, p, p},
    {o, o, b, b, y, b, b, y, b, b, p, p},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {w, w, w, w, _, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::starmode_sprite_normal_walk1_ = {
    {_, _, _, o, o, y, y, e, _, _, _, _},
    {_, _, o, o, y, y, e, p, p, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, o, y, b, e, e, p, _, _, _, _},
    {_, o, o, y, b, e, e, b, p, p, r, _},
    {o, y, y, y, b, b, b, b, p, r, r, r},
    {g, g, y, b, y, b, b, y, b, r, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::starmode_sprite_normal_walk2_ = {
    {_, _, _, y, y, e, e, p, _, _, _, _},
    {_, _, y, y, e, e, p, p, r, r, o, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, y, b, e, p, p, r, _, _, _},
    {_, _, y, e, b, e, p, b, r, o, _, _},
    {_, _, y, e, b, b, b, b, r, o, _, _},
    {_, _, g, g, b, b, b, y, b, o, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::starmode_sprite_normal_walk3_ = {
    {_, _, _, e, e, p, r, r, _, _, _, _},
    {_, _, e, e, p, p, r, o, o, y, y, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, e, p, b, b, _, _, _},
    {_, _, _, b, b, r, o, b, b, _, _, _},
    {_, _, _, b, b, y, p, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};
const vector<vector<int>> MainChar::starmode_sprite_big_walk1_ = {
    {_, _, _, o, o, y, e, e, _, _, _, _},
    {_, _, o, o, y, y, e, p, p, r, r, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, o, y, b, e, e, e, _, _, _, _},
    {_, o, o, y, b, e, e, b, p, p, r, _},
    {o, o, y, y, b, b, b, b, p, p, r, r},
    {o, y, y, b, b, b, b, b, b, p, r, r},
    {y, y, b, b, y, b, b, y, b, b, r, r},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {g, g, g, b, b, b, b, b, b, g, g, g},
    {g, g, b, b, b, b, b, b, b, b, g, g},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, w, w, w, _, _, _, _, w, w, w, _},
    {_, w, w, w, w, _, _, _, w, w, w, w},
};
const vector<vector<int>> MainChar::starmode_sprite_big_walk2_ = {
    {_, _, _, y, y, e, p, p, _, _, _, _},
    {_, _, y, y, e, e, p, r, r, o, o, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, e, b, p, r, r, r, _, _, _},
    {_, _, y, e, b, p, r, b, r, o, _, _},
    {_, _, y, e, b, p, p, b, r, o, _, _},
    {_, _, y, e, b, b, b, b, o, o, _, _},
    {_, _, b, b, b, b, b, y, b, o, _, _},
    {_, _, g, g, b, b, b, b, b, o, _, _},
    {_, _, g, g, g, b, b, b, b, g, _, _},
    {_, _, g, g, b, b, b, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, b, b, b, _, _, b, b, b, _, _},
    {_, _, w, w, w, _, _, w, w, w, _, _},
    {_, _, w, w, w, w, _, w, w, w, w, _},
};
const vector<vector<int>> MainChar::starmode_sprite_big_walk3_ = {
    {_, _, _, e, e, p, r, r, _, _, _, _},
    {_, _, e, e, p, p, r, o, o, y, y, _},
    {_, _, h, h, h, s, s, h, s, _, _, _},
    {_, h, s, h, s, s, s, h, s, s, s, _},
    {_, h, s, h, h, s, s, s, h, s, s, s},
    {_, h, h, s, s, s, s, h, h, h, h, _},
    {_, _, _, s, s, s, s, s, s, s, _, _},
    {_, _, _, b, b, e, p, b, b, _, _, _},
    {_, _, _, b, b, r, o, b, b, _, _, _},
    {_, _, _, b, b, y, e, b, b, _, _, _},
    {_, _, _, b, b, o, p, b, b, _, _, _},
    {_, _, _, b, b, g, g, b, b, _, _, _},
    {_, _, b, b, b, g, g, g, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, b, b, b, g, g, b, b, b, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, b, b, b, b, _, _, _, _},
    {_, _, _, _, w, w, w, w, _, _, _, _},
    {_, _, _, _, w, w, w, w, w, _, _, _},
};